### ISSUE TITLE
doneCmd not working

### ISSUE THREAD

**Issue by MiguelAlcaino** [boypt/simple-torrent#10]
Hi boypt.

I was experimenting with the `doneCmd` option inside the json file but I think I cound't make it run.
Here is what I have done:
1.- I created a simple script to log the variables described in https://github.com/boypt/simple-torrent/wiki/DoneCmdUsage
```
#!/bin/bash

echo $CLD_DIR >> ./done_cmd.log
echo $CLD_PATH >> ./done_cmd.log
echo $CLD_SIZE >> ./done_cmd.log
echo $CLD_TYPE >> ./done_cmd.log
```
2.- I change the doneCmd value in my cloud-torrent.json file
```
"DoneCmd": "/home/myuser/my-logger.sh",
```

But when I add a torrent and then it finishes I don't see anything in my log, it's like the script is not being triggered by simple-torrent. Am I doing something wrong ?

So, would you put an example of how to use the **doneCmd** option ? I would really appreciate that.

Thanks a lot in advance

**Comment by boypt** [comment]
You should check with running logs.

The variable usage is correct, but there are several details that may cause you script not working:

* Option name is `DoneCmd`, not `doneCmd`, check the starting up log that reads in the config.
* Excuteable bits, the script must be excutable (eg, mode 755), check logs with DoneCmd error
* Output location, `"./done_cmd.log"`  is ambigious and may not have permission to write, try with `echo $CLD_DIR >>/tmp/done_cmd.log`, and program also logs the output or error, thats the real help of troblue shooting.

And another note: use double quote with this variables, for there may be spaces in the value, may cause some other trouble.

**Comment by boypt** [comment]
I updated the wiki page with some log example

**Comment by MiguelAlcaino** [comment]
Thanks a lot @boypt , I will try today.

**Comment by enniosousa** [comment]
Hello @boypt !

The ```donecmd``` isn't working to me too. I had tried using docker image and ubuntu install.

```yaml
autostart: true
donecmd: "curl 'https://example.com/hook?access_key=mysecret&param=abcxyz'"
downloaddirectory: /downloads
enableupload: true
incomingport: 50007
obfspreferred: true
obfsrequirepreferred: false
proxyurl: ""
scraperurl: https://raw.githubusercontent.com/boypt/simple-torrent/master/scraper-config.json
seedratio: 0
trackerlisturl: https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
watchdirectory: /torrents
```
