### ISSUE TITLE
cloud torrent with auth not showing login popup

### ISSUE THREAD

**Issue by mdawson16** [boypt/simple-torrent#26]
hi. i create `cloud-torrent -a demo:123` and i open `http://localhost:3000` on browser but is loading nothing happen, maybe login popup not working. please fix it.

**Comment by boypt** [comment]
I guess there's problems during the program running. Provide them or nobody
knows what's going on.

mdawson16 <notifications@github.com> 于2019年10月25日周五 上午10:51写道：

**Comment by rgarrigue** [comment]
Hi

Same issue here using docker.

```
torrent_1      | 2019/10/30 07:22:25 ############# SimpleTorrent ver[] #############
torrent_1      | 2019/10/30 07:22:25 fetchSearchConfig: loading search config from https://gistcdn.githack.com/boypt/9bf0e3e876502ae8e521d9ba0487e0e1/raw/scraper-config.json
torrent_1      | 2019/10/30 07:22:25 Torrent Watcher: watching torrent file in /torrents
torrent_1      | 2019/10/30 07:22:25 Read Config: engine.Config{AutoStart:true, EngineDebug:false, MuteEngineLog:false, ObfsPreferred:true, ObfsRequirePreferred:false, DisableTrackers:false, DisableIPv6:false, DownloadDirectory:"/downloads", WatchDirectory:"/torrents", EnableUpload:true, EnableSeeding:false, IncomingPort:50007, DoneCmd:"", SeedRatio:0, UploadRate:"", DownloadRate:"", TrackerListURL:"", AlwaysAddTrackers:false, ProxyURL:"", RssURL:""}
torrent_1      | 2019/10/30 07:22:25 Listening at http://0.0.0.0:3000
torrent_1      | 2019/10/30 07:22:25 UpdateTrackers: trackers url invalid:  (only https:// supported), extra trackers list now empty.
torrent_1      | 2019/10/30 07:22:25 parse feed addr Invalid 
torrent_1      | 2019/10/30 07:22:26 Loaded new search providers
torrent_1      | 2019-10-30 07:22:27 portfwd.go:30: discovered 0 upnp devices
torrent_1      | 2019-10-30 07:22:27 client.go:328: dht server on [::]:50007: completed bootstrap
torrent_1      | 2019-10-30 07:22:57 client.go:328: dht server on 0.0.0.0:50007: completed bootstrap
```

With .env

```
TITLE=Torrents
PORT=80
AUTH=me:redacted
```

And a piee of my docker-compose.yml

```yaml
  torrent:
    image: boypt/cloud-torrent
    restart: always
    init: true
    networks:
      - web
    env_file: .env.torrent
    volumes:
      - "${DATA_DIR}/torrents:/downloads"
    labels:
      traefik.enable: "true"
      traefik.backend: torrents
      traefik.network: web
      traefik.port: 3000
      traefik.frontend.rule: Host:to.${DOMAIN}
```
